export const SET_MOVIES = 'SET_MOVIES';
export const FETCH_MOVIE_FAIL = 'FETCH_MOVIE_FAIL';
export const NEXT_CARD = 'NEXT_CARD';
export const ANIMATE_CARD = 'ANIMATE_CARD';
export const NEXT_CARD_REJECT = 'NEXT_CARD_REJECT'
export const NEXT_CARD_ACCEPT = 'NEXT_CARD_ACCEPT';
export const ANIMATE_CARD_ACCEPT = 'ANIMATE_CARD_ACCEPT'
export const ANIMATE_CARD_REJECT = 'ANIMATE_CARD_REJECT';